### ISSUE TITLE
Shorthand is not working .sass extension

### ISSUE THREAD

**Issue by wesleyamaro** [kristerkari/react-native-sass-transformer#13]
Hi @kristerkari 

I got 2 problems when using .sass (I did not try using .scss)

1 - Failed build using shorthand properties 
margin: 0 2 14 20
padding: 0 2 14 20
border: 1 solid $color

2 - Failed build when using properties without specifying unit type after the value
margin: 0 2

I tried it using margin, padding, border and text-shadow

**Comment by kristerkari** [comment]
Thanks @wesleyamaro 

Please always use units (px or rem) with the values. The CSS parser that is used does not support numeric values without types.

**Comment by wesleyamaro** [comment]
@kristerkari 

"All dimensions in React Native are unitless, and represent density-independent pixels."

That´s the reason we can not use units type in react native. You can see more details below:
https://facebook.github.io/react-native/docs/height-and-width

**Comment by kristerkari** [comment]
That's when you use Javascript to do styling (which is the default way in React Native). 

My libraries are using the same CSS parser as styled-components, and the idea is to provide a way to do styling that works the same way as in CSS and without using Javascript.

**Comment by wesleyamaro** [comment]
I totally understand what you are saying... 

How are you doing to convert `px` or `rem` used in `.sass` | `.scss` to pixelRatio? If I use `px` in my `.sass` file, it will be rendered to my view as `px` instead of PixelRatio? How it works?

I understand that if your library is for react-native, I think that should be supported because we are going to have a problem in differents screens size if your library does not do that

https://medium.com/@0saurabhgour/react-native-density-independent-pixels-pixelratio-1f10d86f631
