### ISSUE TITLE
The project doesn't accept color in scss.

### ISSUE THREAD

**Issue by diego-aguilar** [kristerkari/react-native-sass-transformer#14]
Hi, in my project I have a issue. "Warning: Failed prop type: Invalid props.style key 'color' supplie to 'View'. ¿Can you help me please?

**Comment by kristerkari** [comment]
That's because React Native's `<View>` element does not support the `color` styling prop. You need to set the color to `<Text>` instead.

**Comment by diego-aguilar** [comment]
Oh, it´s correct, i'm sorry, thanks.

**Comment by kristerkari** [comment]
No worries :) Let me know if you have any other issues 👍
