### ISSUE TITLE
.sass not working

### ISSUE THREAD

**Issue by CrackyStudio** [kristerkari/react-native-sass-transformer#27]
I can use perfectly .scss but .sass for indented syntax seems not working.
Is it only me? Could you provide an example on how to use .sass please?

Thanks in advance,

PS: I use RN 0.60.5 and my globals.d.ts is
```
declare module '*.sass' {
    const content: {[className: string]: any};
    export = content;
}
```

**Comment by kristerkari** [comment]
Last time that I tested it was working fine, but I can test again.

**Comment by CrackyStudio** [comment]
Thanks! If it works, provide an example please :)

**Comment by kristerkari** [comment]
@CrackyStudio here's an example of how to use .sass from my demo project: https://github.com/kristerkari/react-native-css-modules-example/pull/5/files

**Comment by CrackyStudio** [comment]
@kristerkari thanks! I'll try as soon as possible

**Comment by kristerkari** [comment]
Closing this as the issue seems solved.
