### ISSUE TITLE
Support for react-native-web?

### ISSUE THREAD

**Issue by dcangulo** [kristerkari/react-native-sass-transformer#37]
I have tried using this on react-native-web and the style object is empty, however it works on iOS perfectly.

Does this intended to support react-native-web or not?

Anyway, thanks for this module. I have been using this for the past year.

**Comment by kristerkari** [comment]
Hi @dcangulo, there is support for react-native-web, but you have to use CSS modules to do that: https://github.com/kristerkari/react-native-css-modules

**Comment by dcangulo** [comment]
I see. Thanks. :)
