### ISSUE TITLE
Platform-specific properties

### ISSUE THREAD

**Issue by ADavidLiu** [kristerkari/react-native-sass-transformer#38]
How would I go about applying platform-specific styles? For example, how could I convert this `box-shadow`:

```
const styles = StyleSheet.create({
    box: {
        shadowColor: "black",
        shadowOpacity: 1,
        shadowRadius: 10,
        shadowOffset: {
            height: 2,
            width: 2
        },
        elevation: 5
    },
});
```

Into something that would go inside a `.scss` file? It looks like simply adding a `box-shadow` equivalent doesn't work either.

**Comment by kristerkari** [comment]
Thanks, the `box-shadow` does work. In your case this would be the CSS to use: 

```css
.box {
  box-shadow: 2px 2px 10px black;
  elevation: 5;
}
```

**Comment by kristerkari** [comment]
I'm guessing that this is resolved now, closing...
