### ISSUE TITLE
Question: Is there someone uses the nest class successfully?

### ISSUE THREAD

**Issue by Irenedan** [kristerkari/react-native-sass-transformer#44]
Hi, Is there someone uses the nest class successfully?
App.scss:

```
.container {
	width: 100px;
	height: 100px;
	background-color: black;

	.test {
		color: red;
	}
}

```

**Comment by kristerkari** [comment]
@Irenedan sorry for the late reply. It's not possible to nest classes in React Native. That's why it does not work.

**Comment by VityaSchel** [comment]
I posted workaround in #28 https://github.com/kristerkari/react-native-sass-transformer/issues/28#issuecomment-1100724871
