### ISSUE TITLE
Jest setup

### ISSUE THREAD

**Issue by almeidabbm** [kristerkari/react-native-sass-transformer#52]
Not quite an issue, more of a question...

I haven't been able to go around the `.scss` imports when using Jest for tests.
A solution that I have yet to try is to add `moduleNameMapper` like:
```json
"moduleNameMapper":  {
    "something.scss": "<rootDir>/path/to/something.js"
}
```

Wondering how you have been dealing with this scenario

**Comment by kristerkari** [comment]
This a good way to handle the css files in the test. )
