### ISSUE TITLE
React Native 0.73 babel package rename

### ISSUE THREAD

**Issue by Jankku** [kristerkari/react-native-sass-transformer#99]
Hi, I encountered an issue while building RN 0.73 app:
`Failed to construct transformer:  Error: Cannot find module 'metro-react-native-babel-transformer'`

Versions:
`"react-native": "0.73.4"`
`"react-native-sass-transformer": "^2.0.0"`

Here is the changelog and the fix:
`metro-react-native-babel-transformer -> @react-native/metro-babel-transformer`
https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#babel-package-renames

Thank you in advance!

**Comment by kristerkari** [comment]
Thanks! I guess I'll need to release a new version.

**Comment by kristerkari** [comment]
New version out with a fix:
https://github.com/kristerkari/react-native-sass-transformer/releases/tag/v2.1.0
